# Generated by Django 5.2.14 on 2026-06-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('GIRA', 'Gira'), ('FESTA', 'Festa'), ('TRABALHO', 'Trabalho Especial'), ('REUNIAO', 'Reunião')], max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('nome_religioso', models.CharField(blank=True, max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_entrada', models.DateField(auto_now_add=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Financeiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Doação/Mensalidade)'), ('SAIDA', 'Saída (Despesa)')], max_length=10)),
                ('data', models.DateField(auto_now_add=True)),
                ('medium', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.medium')),
            ],
        ),
        migrations.CreateModel(
            name='Presenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=False)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.evento')),
                ('medium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.medium')),
            ],
            options={
                'unique_together': {('medium', 'evento')},
            },
        ),
    ]
