# Generated by Django 5.2.14 on 2026-06-01 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('quantidade_minima', models.IntegerField(default=5, help_text='Aviso quando o estoque estiver abaixo disso')),
                ('unidade_medida', models.CharField(default='unidade', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada (Compra/Doação)'), ('SAIDA', 'Saída (Uso/Perda)')], max_length=10)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.material')),
            ],
        ),
    ]
