# Generated by Django 5.2.14 on 2026-06-02 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_material_movimentacaoestoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cambone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, help_text='Ex: Cambone de Esquerda, Cambone de Direita', max_length=100)),
                ('data_admissao', models.DateField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('medium', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cambone', to='management.medium')),
            ],
        ),
    ]
