# Generated by Django 5.2.14 on 2026-06-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_cambone'),
    ]

    operations = [
        migrations.AddField(
            model_name='medium',
            name='cargo',
            field=models.CharField(blank=True, help_text='Cargo ou função específica dentro do papel', max_length=100),
        ),
        migrations.AddField(
            model_name='medium',
            name='papel',
            field=models.CharField(choices=[('MEMBRO', 'Membro'), ('CAMBONE', 'Cambone'), ('COORDENADOR', 'Coordenador'), ('DIRECAO', 'Direção'), ('ADMINISTRATIVO', 'Administrativo'), ('OUTRO', 'Outro')], default='MEMBRO', help_text='Função do colaborador dentro do centro', max_length=20),
        ),
        migrations.DeleteModel(
            name='Cambone',
        ),
    ]
