# Generated by Django 5.2.14 on 2026-06-10 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('LIMPEZA', 'Banho de Limpeza'), ('PODER', 'Banho de Poder'), ('PROTECAO', 'Banho de Proteção'), ('SAUDE', 'Banho de Saúde'), ('OUTRO', 'Outro')], max_length=20)),
                ('data', models.DateField()),
                ('horario', models.TimeField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('medium', models.ForeignKey(blank=True, help_text='Responsável ou atendente do banho', null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.medium')),
            ],
        ),
    ]
