# Generated by Django 5.2.14 on 2026-06-14 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_banho'),
    ]

    operations = [
        migrations.AddField(
            model_name='banho',
            name='entidade',
            field=models.CharField(blank=True, help_text='Entidade associada ao banho', max_length=100),
        ),
    ]
