# Generated by Django 5.2.14 on 2026-06-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_banho_entidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='gira_concluida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_fim',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='hora_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='recados_entidades',
            field=models.TextField(blank=True),
        ),
    ]
