# Generated by Django 5.2.14 on 2026-06-27 03:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_activitylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='action_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action_label'], name='management__action__fb8cb7_idx'),
        ),
    ]
