# Generated by Django 5.2.14 on 2026-07-07 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_activitylog_action_label_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('GERADA', 'Gerada'), ('EM_ANDAMENTO', 'Em andamento'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='GERADA', max_length=20)),
                ('total_previsto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_compra', to='management.medium')),
            ],
        ),
        migrations.CreateModel(
            name='ListaCompraItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_nome', models.CharField(max_length=100)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('quantidade_atual', models.IntegerField()),
                ('quantidade_minima', models.IntegerField()),
                ('unidade_medida', models.CharField(max_length=20)),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='management.listacompra')),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.material')),
            ],
        ),
    ]
